<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ONX100.Communication\ONX100.Communication.csproj" />
    <ProjectReference Include="..\ONX100.Models\ONX100.Models.csproj" />
  </ItemGroup>

</Project>
